import { chromium } from "playwright-core";
import { fileURLToPath } from "node:url";
const OUT = fileURLToPath(new URL("../shots/", import.meta.url));
const browser = await chromium.launch({ channel: "msedge", headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto("http://localhost:3100/", { waitUntil: "networkidle" });
await page.waitForTimeout(2200);
await page.getByRole("button", { name: /Open Ask Talha assistant/ }).click();
await page.waitForTimeout(900);
await page.locator("#ask-talha-input").fill("Tell me about the malaria project.");
await page.keyboard.press("Enter");
await page.waitForTimeout(2500);
await page.locator("#ask-talha-input").fill("Why does monolayer detection come first?");
await page.keyboard.press("Enter");
await page.waitForTimeout(2200);
const ctx = await page.evaluate(() => document.querySelector("[role='dialog'] [aria-live='polite']").innerText);
console.log("follow-up context resolution:", ctx.includes("cells it sees are separated") ? "CORRECT ✓" : "check");
await page.screenshot({ path: `${OUT}60-chat-desktop.png` });
await page.close();

const m = await browser.newPage({ viewport: { width: 390, height: 844 } });
await m.goto("http://localhost:3100/", { waitUntil: "networkidle" });
await m.waitForTimeout(2200);
await m.getByRole("button", { name: /Open Ask Talha assistant/ }).click();
await m.waitForTimeout(900);
await m.screenshot({ path: `${OUT}61-chat-mobile.png` });
const mo = await m.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth);
console.log("mobile panel overflow:", mo ? "❌" : "none");
await browser.close();
console.log("DONE");
